name: Run Web Scraper

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 every Monday
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
    - name: Run scraper
      env:
        LC_USERNAME: ${{ secrets.LC_USERNAME }}
        LC_PASSWORD: ${{ secrets.LC_PASSWORD }}
      run: python your_script_name.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: downloaded-file
        path: /path/to/download/directory/*  # Adjust this path
