name: Run Scraper and Email Results
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: Reason for running the workflow
        required: false
        default: Manual trigger
  schedule:
    - cron: '0 6 * * 5'  # Runs at 06:00 UTC every Friday
jobs:
  run-scraper-and-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
      - name: Setup GeckoDriver
        uses: browser-actions/setup-geckodriver@latest
      - name: Check Firefox and GeckoDriver versions
        run: |
          firefox --version
          geckodriver --version
      - name: Run scraper script
        env:
          LC_USERNAME: ${{ secrets.LC_USERNAME }}
          LC_PASSWORD: ${{ secrets.LC_PASSWORD }}
        run: python scrapy.py
      - name: Send email with attachment
        env:
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python send_email.py
      - name: Upload downloaded files
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-files
          path: /github/workspace/downloads/*.json
      - name: Log manual trigger reason
        if: github.event_name == 'workflow_dispatch'
        run: echo "Workflow was manually triggered. Reason - ${{
          github.event.inputs.reason || 'No reason provided' }}"
